from pathlib import Path

p = Path('09-06-26-17-01_AWS_VPC_Route_Server_NVA_Dynamic_Service_Insertion_Deep_Dive.md')
s = p.read_text()
marker = '## 1. Executive summary\n'
if s.count(marker) != 1:
    raise SystemExit(f'Expected one executive-summary marker, found {s.count(marker)}')

toc = '''## Table of contents

- [1. Executive summary](#1-executive-summary)
- [2. Terminology and component model](#2-terminology-and-component-model)
  - [What Route Server changes—and what it does not](#what-route-server-changesand-what-it-does-not)
- [3. Core control-plane sequence](#3-core-control-plane-sequence)
- [4. Architecture A — same-VPC publicly reachable application behind active/standby firewalls](#4-architecture-a--same-vpc-publicly-reachable-application-behind-activestandby-firewalls)
  - [4.1 Route ownership — the key mental model](#41-route-ownership--the-key-mental-model)
  - [4.2 What the firewalls advertise](#42-what-the-firewalls-advertise)
  - [4.3 Inbound flow — no firewall DNAT required](#43-inbound-flow--no-firewall-dnat-required)
  - [4.4 Return and outbound flow](#44-return-and-outbound-flow)
  - [4.5 Firewall failure and BGP/BFD convergence](#45-firewall-failure-and-bgpbfd-convergence)
  - [4.6 Scope limitation — same VPC versus centralized remote-spoke ingress](#46-scope-limitation--same-vpc-versus-centralized-remote-spoke-ingress)
- [5. Active/standby BGP design](#5-activestandby-bgp-design)
  - [Failure sequence with BFD](#failure-sequence-with-bfd)
- [6. Architecture B — Centralized inspection with AWS Transit Gateway](#6-architecture-b--centralized-inspection-with-aws-transit-gateway)
  - [AWS July 2026 reference addressing](#aws-july-2026-reference-addressing)
  - [Transit Gateway route-table split](#transit-gateway-route-table-split)
  - [Inspection VPC TGW subnet route table](#inspection-vpc-tgw-subnet-route-table)
  - [Firewall subnet route table](#firewall-subnet-route-table)
- [7. East-west packet walk: Spoke1 → Spoke2](#7-east-west-packet-walk-spoke1--spoke2)
- [8. North-south egress packet walk: Spoke1 → Internet](#8-north-south-egress-packet-walk-spoke1--internet)
- [9. Direct Connect and Site-to-Site VPN enforcement](#9-direct-connect-and-site-to-site-vpn-enforcement)
  - [Direct Connect Transit VIF](#direct-connect-transit-vif)
  - [Site-to-Site VPN](#site-to-site-vpn)
  - [Important unsupported/incorrect assumption](#important-unsupportedincorrect-assumption)
- [10. Architecture C — Dual Route Servers for AZ affinity](#10-architecture-c--dual-route-servers-for-az-affinity)
  - [BGP advertisement matrix](#bgp-advertisement-matrix)
- [11. AWS CLI deployment — Route Server control plane](#11-aws-cli-deployment--route-server-control-plane)
  - [11.1 Create the Route Server](#111-create-the-route-server)
  - [11.2 Associate it with the Inspection VPC](#112-associate-it-with-the-inspection-vpc)
  - [11.3 Create redundant Route Server Endpoints](#113-create-redundant-route-server-endpoints)
  - [11.4 Create a peer for an NVA](#114-create-a-peer-for-an-nva)
  - [11.5 Enable propagation to the interception route table](#115-enable-propagation-to-the-interception-route-table)
  - [11.6 Inspect the Route Server routing database](#116-inspect-the-route-server-routing-database)
- [12. Example NVA BGP policy logic](#12-example-nva-bgp-policy-logic)
- [13. Route-table interaction details](#13-route-table-interaction-details)
- [14. BFD, BGP keepalives, and convergence](#14-bfd-bgp-keepalives-and-convergence)
- [15. Route persistence options](#15-route-persistence-options)
- [16. Security groups, NACLs, source/destination check, and forwarding](#16-security-groups-nacls-sourcedestination-check-and-forwarding)
- [17. NAT design](#17-nat-design)
- [18. MTU and packet-size considerations](#18-mtu-and-packet-size-considerations)
- [19. Quotas and scale](#19-quotas-and-scale)
- [20. Verification runbook](#20-verification-runbook)
  - [20.1 Route Server object state](#201-route-server-object-state)
  - [20.2 Association](#202-association)
  - [20.3 Endpoints](#203-endpoints)
  - [20.4 Peers](#204-peers)
  - [20.5 Appliance BGP state](#205-appliance-bgp-state)
  - [20.6 Advertisement on appliance](#206-advertisement-on-appliance)
  - [20.7 Route Server RIB/FIB](#207-route-server-ribfib)
  - [20.8 Propagation state](#208-propagation-state)
  - [20.9 Actual VPC route table](#209-actual-vpc-route-table)
  - [20.10 Peer logs](#2010-peer-logs)
- [21. Failover test procedure](#21-failover-test-procedure)
- [22. Troubleshooting by symptom](#22-troubleshooting-by-symptom)
- [23. Common mistakes](#23-common-mistakes)
- [24. VPC Route Server vs Gateway Load Balancer](#24-vpc-route-server-vs-gateway-load-balancer)
- [25. Reasonable inferences and design guidance](#25-reasonable-inferences-and-design-guidance)
- [26. Design checklist](#26-design-checklist)
- [Sources](#sources)

---

'''

if '## Table of contents\n' in s:
    raise SystemExit('TOC already exists')
s = s.replace(marker, toc + marker, 1)
p.write_text(s)
