from pathlib import Path
p=Path('09-07-26-07-03_Palo_Alto_Networks_Firewalling_in_GCP_Deep_Dive.md')
s=p.read_text()
old='''  - [7.8 Internet ingress — Internet to published workload](#78-internet-ingress--internet-to-published-workload)\n    - [7.8.9 Can the same VM-Series fleet handle NSI and Internet ingress?](#789-can-the-same-vm-series-fleet-handle-nsi-and-internet-ingress)\n  - [7.8.1 Concrete Internet-ingress example](#781-concrete-internet-ingress-example)\n  - [7.8.2 Create the private application](#782-create-the-private-application)\n  - [7.8.3 Create an Internet-facing forwarding rule for the application](#783-create-an-internet-facing-forwarding-rule-for-the-application)\n  - [7.8.4 Configure PAN-OS DNAT and Security policy](#784-configure-pan-os-dnat-and-security-policy)\n  - [7.8.5 Forward packet walk — Internet client to private workload](#785-forward-packet-walk--internet-client-to-private-workload)\n  - [7.8.6 Return packet walk — private workload back to Internet client](#786-return-packet-walk--private-workload-back-to-internet-client)\n  - [7.8.7 Test and verify the published application](#787-test-and-verify-the-published-application)\n  - [7.8.8 Active/passive HA behavior and caveats](#788-activepassive-ha-behavior-and-caveats)\n'''
new='''  - [7.8 Internet ingress — Internet to published workload](#78-internet-ingress--internet-to-published-workload)\n    - [7.8.1 Concrete Internet-ingress example](#781-concrete-internet-ingress-example)\n    - [7.8.2 Create the private application](#782-create-the-private-application)\n    - [7.8.3 Create an Internet-facing forwarding rule for the application](#783-create-an-internet-facing-forwarding-rule-for-the-application)\n    - [7.8.4 Configure PAN-OS DNAT and Security policy](#784-configure-pan-os-dnat-and-security-policy)\n    - [7.8.5 Forward packet walk — Internet client to private workload](#785-forward-packet-walk--internet-client-to-private-workload)\n    - [7.8.6 Return packet walk — private workload back to Internet client](#786-return-packet-walk--private-workload-back-to-internet-client)\n    - [7.8.7 Test and verify the published application](#787-test-and-verify-the-published-application)\n    - [7.8.8 Active/passive HA behavior and caveats](#788-activepassive-ha-behavior-and-caveats)\n    - [7.8.9 Can the same VM-Series fleet handle NSI and Internet ingress?](#789-can-the-same-vm-series-fleet-handle-nsi-and-internet-ingress)\n'''
if old not in s:
    raise SystemExit('target TOC block not found')
s=s.replace(old,new,1)
p.write_text(s)
