frr defaults traditional
hostname RR
log syslog informational
service integrated-vtysh-config
!
interface lo
 ip address 10.255.0.1/32
 ip ospf area 0.0.0.0
!
interface eth0
 description RR-to-E1
 ip address 10.0.0.1/30
 ip ospf area 0.0.0.0
 ip ospf cost 10
 ip ospf network point-to-point
!
interface eth1
 description RR-to-E2
 ip address 10.0.0.5/30
 ip ospf area 0.0.0.0
 ip ospf cost 100
 ip ospf network point-to-point
!
router ospf
 ospf router-id 10.255.0.1
 passive-interface default
 no passive-interface eth0
 no passive-interface eth1
!
router bgp 65000
 bgp router-id 10.255.0.1
 bgp cluster-id 10.255.0.1
 no bgp default ipv4-unicast
 neighbor 10.255.0.11 remote-as 65000
 neighbor 10.255.0.11 update-source lo
 neighbor 10.255.0.12 remote-as 65000
 neighbor 10.255.0.12 update-source lo
 neighbor 10.255.0.21 remote-as 65000
 neighbor 10.255.0.21 update-source lo
 neighbor 10.255.0.22 remote-as 65000
 neighbor 10.255.0.22 update-source lo
 !
 address-family ipv4 unicast
  neighbor 10.255.0.11 activate
  neighbor 10.255.0.11 route-reflector-client
  neighbor 10.255.0.12 activate
  neighbor 10.255.0.12 route-reflector-client
  neighbor 10.255.0.21 activate
  neighbor 10.255.0.21 route-reflector-client
  neighbor 10.255.0.21 addpath-tx-all-paths
  neighbor 10.255.0.22 activate
  neighbor 10.255.0.22 route-reflector-client
  neighbor 10.255.0.22 addpath-tx-all-paths
 exit-address-family
!
end
