name: temp-add-network-automation-toc
on:
  push:
    paths:
      - '.github/workflows/temp_add_network_automation_toc.yml'
permissions:
  contents: write
jobs:
  edit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Add TOC
        run: python3 .github/temp_add_network_automation_toc.py
      - name: Commit update and remove helpers
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add 08-30-26-17-00_network_automation_using_github.md
          git rm .github/temp_add_network_automation_toc.py
          git rm .github/workflows/temp_add_network_automation_toc.yml
          git commit -m 'Add TOC to network automation using GitHub guide'
          git push
